import React from 'react';
import { ShieldAlert, Lock, Info, ExternalLink } from 'lucide-react';

export const Footer: React.FC = () => {
  return (
    <footer className="bg-slate-900 text-slate-400 text-xs py-10 mt-16 border-t border-slate-800">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
          {/* Disclaimer Column */}
          <div className="md:col-span-2 space-y-3">
            <div className="flex items-center space-x-2 text-amber-400 font-semibold text-sm">
              <ShieldAlert className="w-4 h-4" />
              <span>Important Legal Notice & Scope of Service</span>
            </div>
            <p className="leading-relaxed text-slate-300">
              <strong className="text-white">LexiClear provides informational document analysis, not legal advice.</strong>{' '}
              The findings, scores, and plain-English summaries generated by our GenAI engine are designed solely to highlight provisions for your attention and assist your comprehension. They do not constitute a formal legal opinion, attorney-client relationship, or guarantee of contractual enforceability.
            </p>
            <p className="leading-relaxed text-slate-400 text-[11px]">
              Laws and judicial interpretations vary by jurisdiction. For binding legal guidance, dispute advocacy, or high-stakes commercial negotiations, always consult with a licensed attorney qualified in your state or country.
            </p>
          </div>

          {/* Privacy & Trust Column */}
          <div className="space-y-3 bg-slate-800/60 p-4 rounded-xl border border-slate-700/60">
            <div className="flex items-center space-x-2 text-slate-200 font-medium">
              <Lock className="w-4 h-4 text-emerald-400" />
              <span>Data Privacy & Security</span>
            </div>
            <p className="text-[11px] leading-relaxed text-slate-400">
              Your uploaded contracts and files are processed ephemerally in active memory. LexiClear does not sell, log, or train foundational public models on your proprietary legal text.
            </p>
            <div className="text-[11px] text-slate-400 flex items-center space-x-1.5 pt-1">
              <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></span>
              <span>Encrypted processing</span>
            </div>
          </div>
        </div>

        <div className="pt-6 border-t border-slate-800 flex flex-col sm:flex-row items-center justify-between text-slate-400 text-[11px] gap-3">
          <div>
            © {new Date().getFullYear()} LexiClear Co-Pilot. Built with Google Gemini 3.8.
          </div>
          <div className="flex items-center space-x-4">
            <span className="hover:text-slate-300">Privacy Compliant</span>
            <span>•</span>
            <span className="hover:text-slate-300">Strict Document Grounding</span>
            <span>•</span>
            <span className="hover:text-slate-300">Non-Hallucinatory Protocol</span>
          </div>
        </div>
      </div>
    </footer>
  );
};
